### PR TITLE
WebUI : Lifetime exception request interface doesn't properly show errors : Close #1295

### LINKED ISSUE #1295: Lifetime exception request interface doesn't properly show errors
Motivation
----------
Lifetime exception request interface doesn't properly show errors

### PR DESCRIPTION
**Pull request by cserf**
WebUI : Lifetime exception request interface doesn't properly show errors : Close #1295

### CODE REVIEW

File: lib/rucio/web/ui/static/lifetime_exception.js [hunk 1]
```diff
@@ -258,14 +251,15 @@ $(document).ready(function(){
...
                      expires_at: lifetime,
                      success: function(data) {
-                         console.log('New exception created with id ' + data);
                          dialog.dialog( "close");
                          $("#alert_box").html('<div data-alert class="alert-box success radius">The request has been successfully submitted. It will be approved or rejected in the coming days.</div>');
                      },
                      error: function(jqXHR, textStatus, errorThrown) {
-                         console.log('Could not create exception: ' + textStatus);
-                         console.log(errorThrown);
+                         var alert_text = '<div data-alert class="alert-box alert radius"> Problem to create the exception : '
```
Comment (tbeerman) [inline lib/rucio/web/ui/static/lifetime_exception.js:258]: I cannot approve this. The white space there is just wrong!

**Review by tbeerman — DISMISSED** [review]

File: lib/rucio/web/ui/static/lifetime_exception.js (hunk 1 above)
Comment (bari12) [reply lib/rucio/web/ui/static/lifetime_exception.js:258]: @cserf push 😄

Comment (cserf) [reply lib/rucio/web/ui/static/lifetime_exception.js:258]: I won't change anything : there is obviously a space before the colon !

**Review by bari12 — APPROVED** [review]
